# Generated by Django 2.1.5 on 2021-03-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=120, null=True)),
                ('job_company', models.CharField(blank=True, max_length=120, null=True)),
                ('job_city', models.CharField(blank=True, max_length=120, null=True)),
                ('job_email1', models.CharField(blank=True, max_length=60, null=True)),
                ('job_email2', models.CharField(blank=True, max_length=60, null=True)),
                ('job_external_site', models.CharField(blank=True, max_length=120, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('acc_company', models.CharField(blank=True, max_length=60, null=True)),
                ('acc_comany_size', models.CharField(blank=True, max_length=60, null=True)),
                ('acc_name', models.CharField(blank=True, max_length=60, null=True)),
                ('acc_phone', models.CharField(blank=True, max_length=60, null=True)),
                ('acc_hear', models.CharField(blank=True, max_length=60, null=True)),
                ('billing_type', models.CharField(blank=True, max_length=60, null=True)),
                ('application_type', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
