# Generated by Django 2.1.5 on 2021-03-28 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='acc_comany_size',
            new_name='acc_company_size',
        ),
    ]
