# Generated by Django 2.1.5 on 2021-03-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
